parameters:
    # contact email address
    fop_reviews.emails.contact_email: eugenykr@gmail.com
easy_admin:
    entities:
        - FOP\ReviewsBundle\Entity\Organization
        - FOP\ReviewsBundle\Entity\Review